- name: Install and configure Prometheus
  hosts: prometheus
  become: true

  tasks:
    - name: Update system packages
      yum:
        name: "*"
        state: latest

    - name: Install dependencies
      yum:
        name:
          - wget
          - tar
        state: present

    - name: Download Prometheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.51.2/prometheus-2.51.2.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus archive
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Create symbolic link for Prometheus binary
      file:
        src: /opt/prometheus-2.51.2.linux-amd64/prometheus
        dest: /usr/local/bin/prometheus
        state: link

    - name: Create Prometheus systemd service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/opt/prometheus-2.51.2.linux-amd64/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and enable Prometheus
      systemd:
        daemon_reload: yes
        name: prometheus
        enabled: yes
        state: started

    - name: Copy templated prometheus.yml with node targets
      template:
        src: templates/prometheus.yml.j2
        dest: /opt/prometheus-2.51.2.linux-amd64/prometheus.yml
      notify: Restart Prometheus

  handlers:
    - name: Restart Prometheus
      systemd:
        name: prometheus
        state: restarted
